### ISSUE TITLE
Update docker image

### ISSUE THREAD

**Issue by westonsteimel** [aquasecurity/kube-hunter#103]
As a follow-up to #41, the docker image should at some point be updated to use some version of python 3.  Also, alpine3.9 has been released.  So the following questions arise

* Which version of python3 should be used in the docker image?
* should alpine be updated from 3.8 to 3.9?

For my testing of the python3 changes, I used a docker image with `python:3.7.2-alpine3.9`, so I'm fairly confident that all works, but it may make sense to use something else for your official image.  I see that python3.6 is used in Travis, so perhaps it would be best to keep python3.6 in the docker image as well. 

It would also be good to update the README to indicate that python 3 is supported now.

**Comment by lizrice** [comment]
All great points, thanks @westonsteimel!

I'm a believer in using up-to-date code unless there's a contra-indication, so I think we should 
* Update travis to run both 3.6 and 3.7
* Use the same base image as you did `python:3.7.2-alpine3.9`, since we know from your testing it works 

I've added "3.x" in the README for now
