### ISSUE TITLE
Log levels broken

### ISSUE THREAD

**Issue by invidian** [aquasecurity/kube-hunter#292]
### What happened

It seems that since fe3dba90d8cc6f947846e6a099a2562e7c2f88b1, `--log DEBUG` has no effect when running `kube-hunter`.

Steps to reproduce:
1. Checkout repository
2. `docker run -it $(docker build . | tail -n 1 | cut -d" " -f3) --log DEBUG --pod`

Reverting to fd4d79a8534fe3967162c18770a208871d8403c9 restores proper logging behavior.

### Expected behavior

Debug messages should show up when `--log DEBUG` is specified.

**Comment by iYehuda** [comment]
Hi @invidian !

Thanks for reporting!
This is surely a regression since #283.
The bug origins in a call to `logging.basicConfig` being done before the [configuration set](https://github.com/aquasecurity/kube-hunter/blob/fe187bc50a3492c84e3bf5f79743a4f163f5b413/kube_hunter/__main__.py#L20).
We should avoid using `logging` default logger and use a custom one to prevent unexpected behavior.
