### ISSUE TITLE
git clone from Readme does not work

### ISSUE THREAD

**Issue by ramshazar** [aquasecurity/kube-hunter#38]
The git clone in the readme does not work.
https://github.com/aquasecurity/kube-hunter/blame/master/README.md#L75

`git clone git@github.com:aquasecurity/kube-hunter.git thiswillnotwork
Cloning into 'thiswillnotwork'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.`

git clone via https works fine:
`git clone https://github.com/aquasecurity/kube-hunter.git
Cloning into 'kube-hunter'...
remote: Counting objects: 999, done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 999 (delta 1), reused 3 (delta 1), pack-reused 988
Receiving objects: 100% (999/999), 177.52 KiB | 0 bytes/s, done.
Resolving deltas: 100% (546/546), done.`

**Comment by WesleyCharlesBlake** [comment]
I dont think this is an issue with the project , but more your git config,

```bash
$ git clone git@github.com:aquasecurity/kube-hunter.git thiswillnotwork
Cloning into 'thiswillnotwork'...
remote: Counting objects: 999, done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 999 (delta 1), reused 3 (delta 1), pack-reused 988
Receiving objects: 100% (999/999), 177.52 KiB | 115.00 KiB/s, done.
Resolving deltas: 100% (546/546), done.
```

I can clone just fine. The reason that git-ssh wont work for you is because you are probably missing your SSH keys configured to your GitHub account.

The ]GitHub ssh](https://help.github.com/articles/set-up-git/) setup mentions testing your GitHub connection with:
```$ ssh -T git@github.com
Hi WesleyCharlesBlake! You've successfully authenticated, but GitHub does not provide shell access.```

If that fails, you have an issue with your SSH keys

**Comment by lizrice** [comment]
Thanks @WesleyCharlesBlake! I'm closing this one as those instructions should resolve the problem.
