### ISSUE TITLE
Provide metrics endpoint

### ISSUE THREAD

**Issue by swade1987** [aquasecurity/kube-hunter#79]
Provide an endpoint which Prometheus can scrape to allow real-time alerting of potential vulnerabilities.

**Comment by itaysk** [comment]
thanks @swade1987 for the suggestion. I'd like to clarify this request:
kube-hunter is a one time job that runs, reports, and dies. I don't think exposing metrics from kube-hunter is useful there's a good chance it will finish before Prometheus will be able to scrape it. Once thing we could do, it maybe push to a push gateway.

**Comment by swade1987** [comment]
@itaysk I think the ability to easily configure kube-hunter to push metrics to the pushgateway makes sense.

**Comment by Nishanth-developer** [comment]
I just want to export the metrics of the kube hunter pod to use in grafana dashboards and for other purposes. After researching a lot, I couldn't find any **metrics exporter** for kube hunter and I have no idea how to create a custom metrics exporter because of lack of resources online at the begineer level. I would be so glad if you can give a solution for this issue, by providing a **kube hunter metrics exporter** so that the results can be visualized in **grafana dashboards**.
